[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_unflags =
    -std=gnu++11

monitor_speed = 115200
build_flags =
  -std=gnu++17
  -DCORE_DEBUG_LEVEL=3
  ; USB-CDC Serial auf vielen S3 Boards sinnvoll:
  -DARDUINO_USB_CDC_ON_BOOT=1

  ; Onboard RGB LED 
  -DLED_PIN=48
  -DLED_COUNT=1
  -DLED_BRIGHTNESS=255

; optional: schnelleres Upload
upload_speed = 921600

lib_deps =
  adafruit/Adafruit NeoPixel@^1.12.0